#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  tabelas.py
#  
#  Copyright 2016 lykos users <lykos@linux-714r.site>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

# Opcao para apagar todas as tabelas
# drop table cia,grupofab,parametr,produtos,tributos,usuario,idavs,didavs,cdavs,dcdavs,clientes,receber,conta,ocorren,tdavs,ccmp,iccmp,fornecedor,apagar,sansu,modperfil,auremoto,municipio,romaneio,nfes,plcontas,sefazxml,tmpclientes,estoque,fretes,entregas;


from lobo import *
import datetime
import os
from decimal import *

os.system("clear")

conn = sqldb()
sql  = conn.dbc("Produtos, Alterar Estoque Fisico",1)
grv  = True
saida = input("1-Criar tabelas\n2-Adiconar campos novos nas tabelas\n\nOpção: ")

bancos = {}

#--: Inicio de definicao das tabelas
bancos['parametros'] = """
		create table IF NOT EXISTS parametr (pr_regi int(8) not null auto_increment primary key,
		pr_cdpd int(7)      default 0,
		pr_usid int(8)      default 0,
		pr_barr int(7)      default 0,
		pr_ndav int(13)     default 0,
		pr_ncmd int(14)     default 0,                                             
		pr_tdav int(12)     default 0,
		pr_clie int(12)     default 0,                                             
		pr_rdap text,
		pr_pros varchar(1)  default '1',
		pr_phos varchar(50) default '',
		pr_pusa varchar(12) default '',
		pr_psen varchar(12)	default '',
		pr_sqlb varchar(20) default '',
		pr_nfen int(9)      default 0,
		pr_nfse int(3)      default 55,
		pr_nfim int(1)      default 1,
		pr_nfci int(1)      default 1,	
		pr_nffi int(1)      default 1,
		pr_nfem int(1)      default 0,
		pr_nfrd text,
		pr_nfvs varchar(4)  default '',
		pr_rece int(11)     default 0,
		pr_devv int(10)     default 0,
		pr_comp int(10)     default 0,
		pr_bord int(10)     default 0,
		pr_borb int(10)     default 0,
		pr_cona int(8)      default 0,
		pr_roma int(10)     default 0,
		pr_bole int(10)     default 0,
		pr_entr date default '00-00-0000',
		pr_pblq MEDIUMBLOB,
		pr_apaf MEDIUMBLOB,
		pr_fcum MEDIUMBLOB);
		"""

bancos['empresa'] = """
		create table IF NOT EXISTS cia (ep_regi int(3) not null auto_increment primary key,
		ep_nome varchar(50)  default '',
		ep_ende varchar(50)  default '',
		ep_bair varchar(20)  default '',
		ep_cida varchar(20)  default '',
		ep_cepe varchar(9)   default '',
		ep_esta varchar(2)   default '',
		ep_com1 varchar(5)   default '',
		ep_com2 varchar(20)  default '',
		ep_cnpj varchar(14)  default '',
		ep_tels varchar(60)  default '',
		ep_iest varchar(14)  default '',
		ep_imun varchar(14)  default '',
		ep_ibge varchar(7)   default '',
		ep_fant varchar(20)  default '',
		ep_logo varchar(30)  default '',
		ep_inde varchar(5)   default '',
		ep_imdv varchar(200) default '',
		ep_iexp varchar(200) default '',
		ep_arre varchar(1)   default '',
		ep_ddev varchar(3)   default '',
		ep_opaf varchar(1)   default '1',
		ep_ddan varchar(1)   default 'F',
		ep_vdin varchar(1)   default 'F',
		ep_resd varchar(2)   default '',
		ep_econ varchar(120) default '',
		ep_adic text,
		ep_nfes int(10)      default 0,
		ep_nfce int(10)      default 0,
		ep_svem text,
		ep_dnfe text,
		ep_sqls text,
		ep_sqlf text,
		ep_fema varchar(1)   default 'F',
		ep_rese varchar(2)   default '',
		ep_psis text,
		ep_darf text,
		ep_atrm text,
		ep_acbr text,
		ep_admi varchar(8) default '',
		ep_prdo text,
		ep_pjba MEDIUMBLOB,
		ep_bkcl MEDIUMBLOB,
		ep_mdfe int(10) default 0,
		ep_smdf varchar(3) default '');
		"""

bancos['grupos'] = """
		create table IF NOT EXISTS grupofab (fg_regi int(8) not null auto_increment primary key,
		fg_cdpd varchar(1)   default '',
		fg_desc varchar(20)  default '',
		fg_prin varchar(100) default '',
		fg_fila varchar(100) default '',
		fg_info MEDIUMBLOB);
		"""

bancos['tributos'] = """
		create table IF NOT EXISTS tributos (cd_regi int(8) not null auto_increment primary key,
		cd_cdpd varchar(1)    default '',
		cd_codi varchar(30)   default '',
		cd_cdt1 varchar(12)   default '',
		cd_cdt2 varchar(12)   default '',
		cd_cdt3 varchar(12)   default '',
		cd_cdt4 varchar(12)   default '',
		cd_desc varchar(2000) default '',
		cd_oper varchar(60)   default '',
		cd_icms decimal(6,2) default 0,
		cd_tipi decimal(6,2) default 0,
		cd_mvad decimal(6,2) default 0,
		cd_mvaf decimal(6,2) default 0,
		cd_piss decimal(6,2) default 0,
		cd_conf decimal(6,2) default 0,
		cd_imp1 decimal(6,2) default 0,
		cd_imp2 decimal(6,2) default 0,
		cd_imp3 decimal(6,2) default 0,
		cd_ricm decimal(6,2) default 0,
		cd_rstb decimal(6,2) default 0,
		cd_imp4 decimal(6,2) default 0,
		cd_imp5 decimal(6,2) default 0,
		cd_auto varchar(20)  default '');
		"""

bancos['usuarios'] = """
		create table IF NOT EXISTS usuario (us_regi int(4) not null auto_increment primary key,
		us_logi varchar(12)  default '',
		us_nome varchar(50)  default '',
		us_senh varchar(20)  default '',
		us_empr varchar(3)   default '',
		us_inde varchar(5)   default '',
		us_ecfs varchar(30)  default '',
		us_emai varchar(200) default '',
		us_ipad varchar(100) default '',
		us_assi varchar(200) default '',
		us_shem varchar(50)  default '',
		us_desc decimal(6,2) not null default 0,
		us_auto varchar(1)   default '',
		us_ecfi varchar(1)   default 'F',
		us_gave varchar(1)   default 'F', 
		us_pnfc varchar(4)   default '', 
		us_nfce varchar(1)   default 'F',
		us_seri varchar(3)   default '',                                         
		us_para MEDIUMBLOB,
		us_nnfc int(9),
		us_nfcs varchar(3),
		us_proh varchar(1),
		us_ndav int(7));
		"""

bancos['produtos'] = """
		create table IF NOT EXISTS produtos (pd_regi int(8) not null auto_increment primary key,
		pd_fili varchar(3)  not null default '',
		pd_codi varchar(14) not null,
		pd_nome varchar(120) not null,
		pd_cara varchar(50) default '',
		pd_refe varchar(30) default '',                                                 
		pd_barr varchar(14) default '',
		pd_unid varchar(2) default 'UN',
		pd_nmgr varchar(20) default '',
		pd_fabr varchar(20) default '',
		pd_intc varchar(20) default '',
		pd_ende varchar(30) default '',
		pd_gara varchar(2) default '',
		pd_pesb decimal(8,3) not null default 0,
		pd_pesl decimal(8,3) not null default 0,
		pd_estf decimal(15,4) not null default 0,
		pd_estm decimal(15,4) not null default 0,
		pd_estx decimal(15,4) not null default 0,
		pd_estt decimal(15,4) not null default 0,
		pd_virt decimal(15,4) not null default 0,
		pd_marg decimal(8,3) not null default 0,
		pd_mrse decimal(6,2) not null default 0,
		pd_mfin decimal(6,2) not null default 0,
		pd_pcom decimal(15,4) not null default 0,
		pd_pcus decimal(15,4) not null default 0,
		pd_cusm decimal(15,4) not null default 0,
		pd_mdun varchar(1) default '1',
		pd_coms decimal(6,2) not null default 0,
		pd_tpr1 decimal(15,3) not null default 0,
		pd_tpr2 decimal(15,3) not null default 0,
		pd_tpr3 decimal(15,3) not null default 0,
		pd_tpr4 decimal(15,3) not null default 0,
		pd_tpr5 decimal(15,3) not null default 0,
		pd_tpr6 decimal(15,3) not null default 0,
		pd_vdp1 decimal(15,3) not null default 0,
		pd_vdp2 decimal(15,3) not null default 0,
		pd_vdp3 decimal(15,3) not null default 0,
		pd_vdp4 decimal(15,3) not null default 0,
		pd_vdp5 decimal(15,3) not null default 0,
		pd_vdp6 decimal(15,3) not null default 0,
		pd_cont varchar(1) default '',
		pd_nimp varchar(2) default '',
		pd_prom varchar(1) default '',
		pd_pdsc varchar(1) default '',
		pd_prod varchar(1) default '',
		pd_bene varchar(1) default '',
		pd_cupf varchar(1)    default 'N',
		pd_cfis varchar(30)   default '',
		pd_has1 varchar(256)  default '',                                               
		pd_has2 varchar(256)  default '',
		pd_has3 varchar(256)  default '',
		pd_canc varchar(1)    default '',
		pd_idfi varchar(5)    default '',
		pd_cfir varchar(30)   default '',
		pd_esrf decimal(15,4) not null default 0,
		pd_mark varchar(25)   default '',
		pd_ula1 varchar(32)   default '',
		pd_ula2 varchar(32)   default '',
		pd_funa varchar(32)   default '',
		pd_frac varchar(1)    default '',
		pd_docf varchar(14)   default '',
		pd_sug1 varchar(20)   default '',
		pd_sug2 varchar(20)   default '',
		pd_ulvd text,
		pd_ulcm text,
		pd_ulac text,
		pd_simi text,
		pd_agre text,
		pd_marc varchar(1)    default "T",
		pd_cfor varchar(30)   default "",
		pd_acds varchar(1)    default "A",
		pd_fbar varchar(30)   default "",                                               
		pd_pdof varchar(1)    default "F",
		pd_marp text,
		pd_stcm decimal(6,2) not null default 0,
		pd_qtem varchar(10)    default '',
		pd_altp text,
		pd_ultr text,
		pd_alte varchar(1)   default 'F',
		pd_kitc varchar(1)   default 'F',
		pd_codk text,
		pd_cokt varchar(14)  default '',
		pd_cfsc varchar(30)  default '',
		pd_imag text,
		pd_dtal date default '00-00-0000',
		pd_hcal time default '00:00:00',
		pd_salt varchar(1)   default '',
		pd_dabc text,
		pd_cest varchar(7) default '',                                                  
		pd_para text,
		pd_pcfl MEDIUMBLOB,
		pd_nvdf MEDIUMBLOB,
		pd_endd varchar(30) default '',
		pd_nser varchar(1) default '',
		pd_clou varchar(30) default '',
		pd_lvir varchar(30) default '',
		pd_afat varchar(30) default '',
		INDEX(pd_nome),
		INDEX(pd_codi));
		"""

bancos['items'] = """
		create table IF NOT EXISTS idavs (it_item varchar(3) default '',
		it_fili varchar(3)  default '',
		it_ndav varchar(13) default '',
		it_cmda varchar(13) default '',
		it_cdcl varchar(14) default '',                              
		it_codi varchar(14) default '', 
		it_barr varchar(14) default '',  
		it_nome varchar(120) default '',  
		it_unid varchar(2)  default 'UN',   
		it_fabr varchar(20) default '',  
		it_ende varchar(30) default '',  
		it_prec decimal(15,3) default 0,
		it_quan decimal(15,4) default 0,
		it_subt decimal(15,2) default 0,
		it_vlun decimal(15,4) default 0,                             
		it_clcm decimal(6,3)  default 0,
		it_clla decimal(6,3)  default 0,
		it_clex decimal(6,3)  default 0,
		it_clmt decimal(15,4) default 0,
		it_ctcm decimal(6,3)  default 0,
		it_ctla decimal(6,3)  default 0,
		it_ctex decimal(6,3)  default 0,
		it_ctmt decimal(15,4) default 0,
		it_unpc decimal(15,4) default 0,
		it_mdct varchar(1)    default '1',
		it_obsc text,
		it_vfre decimal(15,2) default 0,
		it_vacr decimal(15,2) default 0,
		it_vdes decimal(15,2) default 0,
		it_pcim decimal(6,2)  default 0,
		it_pric decimal(6,2)  default 0,
		it_pipi decimal(6,2)  default 0,
		it_psub decimal(6,2)  default 0,
		it_piss decimal(6,2)  default 0,
		it_bcim decimal(15,2) default 0,
		it_bric decimal(15,2) default 0,
		it_bipi decimal(15,2) default 0,
		it_bsub decimal(15,2) default 0,
		it_biss decimal(15,2) default 0,
		it_vcim decimal(15,2) default 0,
		it_vric decimal(15,2) default 0,
		it_vipi decimal(15,2) default 0,
		it_vsub decimal(15,2) default 0,
		it_viss decimal(15,2) default 0,
		it_tiat varchar(1)    default '',
		it_vdcd varchar(4)    default '',
		it_nmvd varchar(12)   default '',
		it_usac varchar(12)   default '',
		it_inde varchar(5)    default '',
		it_idfo varchar(5)    default '',
		it_pper decimal(6,2)  default 0,
		it_cper decimal(6,2)  default 0,
		it_pbas decimal(15,2) default 0,
		it_cbas decimal(15,2) default 0,
		it_pval decimal(15,2) default 0,
		it_cval decimal(15,2) default 0,
		it_ncmc varchar(8)    default '',
		it_cfop varchar(4)    default '',
		it_cstc varchar(4)    default '',
		it_cdfi varchar(30)   default '',
		it_pibp decimal(5,2)  default 0,
		it_vibp decimal(10,2) default 0,
		it_entr varchar(40)   default '',
		it_rece varchar(40)	 default '',
		it_qent decimal(15,4) default 0,
		it_iddv varchar(3)    default '',
		it_qtdv decimal(14,4) default 0,
		it_lanc date default '00-00-0000',
		it_horl time default '00:00:00',
		it_qtan decimal(15,4) default 0,
		it_expe varchar(100)  default '',
		it_grup varchar(20)   default '',
		it_sbg1 varchar(20)   default '',
		it_sbg2 varchar(20)   default '',
		it_estf decimal(15,4) not null default 0,
		it_tabe varchar(1)    default '',
		it_reti text,
		it_cprc decimal(15,4) default 0,
		it_ctot decimal(15,2) default 0,
		it_dcan date default '00-00-0000',
		it_hcan time default '00:00:00',
		it_aesf decimal(15,4) not null default 0,
		it_canc varchar(1)    default '',
		it_dado varchar(100)  default'',
		it_clie varchar(120)  default '',
		it_pdof varchar(1)    default "F",
		it_futu varchar(1)    default "F",
		it_tped varchar(1)    default "",
		it_refe varchar(30)   default '',
		it_manu decimal(15,3) default 0,
		it_auto text,
		it_ckit varchar(200)  default '',
		it_qkiv decimal(15,4) default 0,
		it_qtid decimal(15,4) default 0,
		it_dibp MEDIUMBLOB,											
		it_ouin MEDIUMBLOB,
		it_qdvu decimal(14,4) default 0,
		it_part MEDIUMBLOB,
		it_seri MEDIUMBLOB,
		it_emba varchar(100) default '',
		it_comi decimal(6,2) default 0,
		it_eloc decimal(15,4) not null default 0,
		it_idof MEDIUMBLOB,
		it_deso MEDIUMBLOB,
		it_logi decimal(15,4) default 0,
		INDEX (it_ndav),
		INDEX (it_lanc),
		INDEX (it_dcan),
		INDEX (it_lanc,it_codi),
		INDEX (it_codi),
		INDEX (it_nome));
		"""

bancos['ditems'] = """
		create table IF NOT EXISTS didavs (it_item varchar(3) default '',
		it_fili varchar(3)  default '',
		it_ndav varchar(13) default '',
		it_cmda varchar(13) default '',
		it_cdcl varchar(14) default '',                              
		it_codi varchar(14) default '', 
		it_barr varchar(14) default '',  
		it_nome varchar(120) default '',  
		it_unid varchar(2)  default 'UN',   
		it_fabr varchar(20) default '',  
		it_ende varchar(30) default '',  
		it_prec decimal(15,3) default 0,
		it_quan decimal(15,4) default 0,
		it_subt decimal(15,2) default 0,
		it_vlun decimal(15,4) default 0,                             
		it_clcm decimal(6,3)  default 0,
		it_clla decimal(6,3)  default 0,
		it_clex decimal(6,3)  default 0,
		it_clmt decimal(15,4) default 0,
		it_ctcm decimal(6,3)  default 0,
		it_ctla decimal(6,3)  default 0,
		it_ctex decimal(6,3)  default 0,
		it_ctmt decimal(15,4) default 0,
		it_unpc decimal(15,3) default 0,
		it_mdct varchar(1)    default '1',
		it_obsc text,
		it_vfre decimal(15,2) default 0,
		it_vacr decimal(15,2) default 0,
		it_vdes decimal(15,2) default 0,
		it_pcim decimal(6,2)  default 0,
		it_pric decimal(6,2)  default 0,
		it_pipi decimal(6,2)  default 0,
		it_psub decimal(6,2)  default 0,
		it_piss decimal(6,2)  default 0,
		it_bcim decimal(15,2) default 0,
		it_bric decimal(15,2) default 0,
		it_bipi decimal(15,2) default 0,
		it_bsub decimal(15,2) default 0,
		it_biss decimal(15,2) default 0,
		it_vcim decimal(15,2) default 0,
		it_vric decimal(15,2) default 0,
		it_vipi decimal(15,2) default 0,
		it_vsub decimal(15,2) default 0,
		it_viss decimal(15,2) default 0,
		it_tiat varchar(1)    default '',
		it_vdcd varchar(4)    default '',
		it_nmvd varchar(12)   default '',
		it_usac varchar(12)   default '',
		it_inde varchar(5)    default '',
		it_idfo varchar(5)    default '',
		it_pper decimal(6,2)  default 0,
		it_cper decimal(6,2)  default 0,
		it_pbas decimal(15,2) default 0,
		it_cbas decimal(15,2) default 0,
		it_pval decimal(15,2) default 0,
		it_cval decimal(15,2) default 0,
		it_ncmc varchar(8)    default '',
		it_cfop varchar(4)    default '',
		it_cstc varchar(4)    default '',
		it_cdfi varchar(30)   default '',
		it_pibp decimal(5,2)  default 0,
		it_vibp decimal(10,2) default 0,
		it_entr varchar(40)   default '',
		it_rece varchar(40)	 default '',
		it_qent decimal(15,4) default 0,
		it_iddv varchar(3)    default '',
		it_qtdv decimal(14,4) default 0,
		it_lanc date default '00-00-0000',
		it_horl time default '00:00:00',
		it_qtan decimal(15,4) default 0,
		it_expe varchar(100)  default '',
		it_grup varchar(20)   default '',
		it_sbg1 varchar(20)   default '',
		it_sbg2 varchar(20)   default '',
		it_estf decimal(15,4) not null default 0,
		it_tabe varchar(1)    default '',
		it_reti text,
		it_cprc decimal(15,4) default 0,
		it_ctot decimal(15,2) default 0,
		it_dcan date default '00-00-0000',
		it_hcan time default '00:00:00',
		it_aesf decimal(15,4) not null default 0,
		it_canc varchar(1)    default '',
		it_dado varchar(100)  default'',
		it_clie varchar(120)  default '',
		it_pdof varchar(1)    default "F",
		it_futu varchar(1)    default "F",
		it_tped varchar(1)    default "",
		it_refe varchar(30)   default '',
		it_manu decimal(15,3) default 0,
		it_auto text,
		it_ckit varchar(200)  default '',
		it_qkiv decimal(15,4) default 0,
		it_qtid decimal(15,4) default 0,
		it_dibp MEDIUMBLOB,											
		it_ouin MEDIUMBLOB,
		it_qdvu decimal(14,4) default 0,
		it_part MEDIUMBLOB,
		it_seri MEDIUMBLOB,
		it_emba varchar(100) default '',
		it_comi decimal(6,2) default 0,
		it_eloc decimal(15,4) not null default 0,
		it_idof MEDIUMBLOB,
		it_deso MEDIUMBLOB,
		it_logi decimal(15,4) default 0,
		INDEX (it_ndav),		
		INDEX (it_lanc),		
		INDEX (it_dcan),
		INDEX (it_lanc,it_codi),
		INDEX (it_codi),
		INDEX (it_nome));
		"""

bancos['cdavs'] = """
		create table IF NOT EXISTS cdavs (cr_regi int(14) not null auto_increment primary key,
		cr_fili varchar(3)  default '',
		cr_ndav varchar(13) default '',
		cr_cdcl varchar(14) default '',
		cr_nmcl varchar(50) default '',
		cr_facl varchar(20) default '',
		cr_cupo varchar(6)  default '',
		cr_ccan varchar(6)  default '',
		cr_nota varchar(9)  default '',
		cr_udav varchar(20) default '',
		cr_urec varchar(20) default '',
		cr_edav date default '00-00-0000',
		cr_hdav time default '00:00:00',
		cr_erec date default '00-00-0000',
		cr_hrec time default '00:00:00',
		cr_nfem varchar(60)   default '',
		cr_nfca varchar(60)   default '',
		cr_ecem varchar(60)   default '',
		cr_ecca varchar(60)   default '',
		cr_ecan date default '00-00-0000',
		cr_hcan time default '00:00:00',
		cr_entr date default '00-00-0000',
		cr_hent time default '00:00:00',
		cr_vfre decimal(15,2)  default 0,
		cr_vacr decimal(15,2)  default 0,
		cr_vdes decimal(15,2)  default 0,
		cr_vcim decimal(15,2)  default 0,
		cr_vric decimal(15,2)  default 0,
		cr_vipi decimal(15,2)  default 0,
		cr_vsub decimal(15,2)  default 0,
		cr_viss decimal(15,2)  default 0,
		cr_bcim decimal(15,2)  default 0,
		cr_bric decimal(15,2)  default 0,
		cr_bipi decimal(15,2)  default 0,
		cr_bsub decimal(15,2)  default 0,
		cr_biss decimal(15,2)  default 0,
		cr_tpro decimal(15,2) default 0,
		cr_tnot decimal(15,2) default 0,
		cr_refe text,
		cr_docu varchar(14)   default '',
		cr_paga varchar(30)   default '',
		cr_tipo varchar(1)    default '',
		cr_rloc varchar(1)    default '',
		cr_vdcd varchar(4)    default '',
		cr_nmvd varchar(12)   default '',
		cr_usac varchar(12)   default '',
		cr_cxcd varchar(4)    default '',
		cr_rece varchar(30)   default '',
		cr_vlrc decimal(15,2)  default 0,
		cr_vltr decimal(15,2)  default 0,
		cr_ccre decimal(15,2)  default 0,
		cr_cdeb decimal(15,2)  default 0,
		cr_ficx varchar(3)    default '',
		cr_tror decimal(15,2)  default 0,
		cr_inde varchar(5)    default '',
		cr_idfc varchar(5)    default '',
		cr_dinh decimal(15,2)  default 0,
		cr_chav decimal(15,2)  default 0,
		cr_chpr decimal(15,2)  default 0,
		cr_ctcr decimal(15,2)  default 0,
		cr_ctde decimal(15,2)  default 0,
		cr_fatb decimal(15,2)  default 0,
		cr_fatc decimal(15,2)  default 0,
		cr_fina decimal(15,2)  default 0,
		cr_tike decimal(15,2)  default 0,
		cr_pgcr decimal(15,2)  default 0,
		cr_depc decimal(15,2)  default 0,
		cr_ccfe varchar(6)    default '',
		cr_pibc decimal(15,2)  default 0,
		cr_cobc decimal(15,2)  default 0,
		cr_pivl decimal(15,2)  default 0,
		cr_covl decimal(15,2)  default 0,
		cr_ibpt varchar(30)   default '',
		cr_chnf varchar(44)   default '',
		cr_reca varchar(1)    default '',
		cr_cadc varchar(1)    default '',
		cr_ende varchar(4)    default '',
		cr_moti text,
		cr_cdev varchar(13)   default '',
		cr_dmot varchar(30)   default '',
		cr_auto varchar(20)   default '',
		cr_rela varchar(100)  default '',
		cr_hist text,
		cr_loca varchar(30)   default '',
		cr_rcbl decimal(15,2) default 0,
		cr_impr text,
		cr_dade text,
		cr_ebai varchar(20) default '',
		cr_ecid varchar(20) default '',
		cr_ecep varchar(9)  default '',
		cr_roma varchar(10) default '',
		cr_dado text,
		cr_ecfb varchar(20) default '',
		cr_cust decimal(15,2) default 0,
		cr_vazc varchar(1)  default 'F',
		cr_prer MEDIUMBLOB,
		cr_ecfs varchar(3)  default '',
		cr_guap MEDIUMBLOB,
		cr_tfat varchar(1)    default '',
		cr_nfev varchar(100)  default '',
		cr_cont varchar(100)  default '',
		cr_seri varchar(3)    default '',
		cr_comp varchar(120)  default '',
		cr_comg varchar(8)    default '',
		cr_tnfs varchar(1)    default '',
		cr_audv varchar(40)   default '',
		cr_csta varchar(3)    default '',
		cr_vpar MEDIUMBLOB,
		cr_cavu varchar(13) default '',
		cr_dibp MEDIUMBLOB,
		cr_part MEDIUMBLOB,
		cr_mist MEDIUMBLOB,
		cr_vnfe varchar(13) default '',
		cr_vnpr decimal(6,2) default 0,
		cr_stat varchar(40) default '',
		cr_expe MEDIUMBLOB,
		cr_exse MEDIUMBLOB,
		cr_tabe MEDIUMBLOB,
		cr_chcp varchar(44),
		cr_vobs MEDIUMBLOB,
		cr_deso MEDIUMBLOB,
		cr_twtp varchar(1) default '',
		cr_pdwb varchar(30) default '',
		cr_pdor varchar(3) default '', 		
		INDEX(cr_edav),
		INDEX(cr_ndav),
		INDEX(cr_erec),
		INDEX(cr_ecan),
		INDEX(cr_entr),
		INDEX(cr_nmcl),
		INDEX(cr_pdwb,cr_pdor));
		"""


bancos['dcdavs'] = """
		create table IF NOT EXISTS dcdavs (cr_regi int(14) not null auto_increment primary key,
		cr_fili varchar(3)  default '',
		cr_ndav varchar(13) default '',
		cr_cdcl varchar(14) default '',
		cr_nmcl varchar(50) default '',
		cr_facl varchar(20) default '',
		cr_cupo varchar(6)  default '',
		cr_ccan varchar(6)  default '',
		cr_nota varchar(9)  default '',
		cr_udav varchar(20) default '',
		cr_urec varchar(20) default '',
		cr_edav date default '00-00-0000',
		cr_hdav time default '00:00:00',
		cr_erec date default '00-00-0000',
		cr_hrec time default '00:00:00',
		cr_nfem varchar(60)   default '',
		cr_nfca varchar(60)   default '',
		cr_ecem varchar(60)   default '',
		cr_ecca varchar(60)   default '',
		cr_ecan date default '00-00-0000',
		cr_hcan time default '00:00:00',
		cr_entr date default '00-00-0000',
		cr_hent time default '00:00:00',
		cr_vfre decimal(15,2)  default 0,
		cr_vacr decimal(15,2)  default 0,
		cr_vdes decimal(15,2)  default 0,
		cr_vcim decimal(15,2)  default 0,
		cr_vric decimal(15,2)  default 0,
		cr_vipi decimal(15,2)  default 0,
		cr_vsub decimal(15,2)  default 0,
		cr_viss decimal(15,2)  default 0,
		cr_bcim decimal(15,2)  default 0,
		cr_bric decimal(15,2)  default 0,
		cr_bipi decimal(15,2)  default 0,
		cr_bsub decimal(15,2)  default 0,
		cr_biss decimal(15,2)  default 0,
		cr_tpro decimal(15,2) default 0,
		cr_tnot decimal(15,2) default 0,
		cr_refe text,
		cr_docu varchar(14)   default '',
		cr_paga varchar(30)   default '',
		cr_tipo varchar(1)    default '',
		cr_rloc varchar(1)    default '',
		cr_vdcd varchar(4)    default '',
		cr_nmvd varchar(12)   default '',
		cr_usac varchar(12)   default '',
		cr_cxcd varchar(4)    default '',
		cr_rece varchar(30)   default '',
		cr_vlrc decimal(15,2)  default 0,
		cr_vltr decimal(15,2)  default 0,
		cr_ccre decimal(15,2)  default 0,
		cr_cdeb decimal(15,2)  default 0,
		cr_ficx varchar(3)    default '',
		cr_tror decimal(15,2)  default 0,
		cr_inde varchar(5)    default '',
		cr_idfc varchar(5)    default '',
		cr_dinh decimal(15,2)  default 0,
		cr_chav decimal(15,2)  default 0,
		cr_chpr decimal(15,2)  default 0,
		cr_ctcr decimal(15,2)  default 0,
		cr_ctde decimal(15,2)  default 0,
		cr_fatb decimal(15,2)  default 0,
		cr_fatc decimal(15,2)  default 0,
		cr_fina decimal(15,2)  default 0,
		cr_tike decimal(15,2)  default 0,
		cr_pgcr decimal(15,2)  default 0,
		cr_depc decimal(15,2)  default 0,
		cr_ccfe varchar(6)    default '',
		cr_pibc decimal(15,2)  default 0,
		cr_cobc decimal(15,2)  default 0,
		cr_pivl decimal(15,2)  default 0,
		cr_covl decimal(15,2)  default 0,
		cr_ibpt varchar(30)   default '',
		cr_chnf varchar(44)   default '',
		cr_reca varchar(1)    default '',
		cr_cadc varchar(1)    default '',
		cr_ende varchar(4)    default '',
		cr_moti text,
		cr_cdev varchar(13)   default '',
		cr_dmot varchar(30)   default '',
		cr_auto varchar(20)   default '',
		cr_rela varchar(100)  default '',
		cr_hist text,
		cr_loca varchar(30)   default '',
		cr_rcbl decimal(15,2) default 0,
		cr_impr text,
		cr_dade text,
		cr_ebai varchar(20) default '',
		cr_ecid varchar(20) default '',
		cr_ecep varchar(9)  default '',
		cr_roma varchar(10) default '',
		cr_dado text,
		cr_ecfb varchar(20) default '',
		cr_cust decimal(15,2) default 0,
		cr_vazc varchar(1)  default 'F',
		cr_prer MEDIUMBLOB,
		cr_ecfs varchar(3)  default '',
		cr_guap MEDIUMBLOB,
		cr_tfat varchar(1)    default '',
		cr_nfev varchar(100)  default '',
		cr_cont varchar(100)  default '',
		cr_seri varchar(3)    default '',
		cr_comp varchar(120)  default '',
		cr_comg varchar(8)    default '',
		cr_tnfs varchar(1)    default '',
		cr_audv varchar(40)   default '',
		cr_csta varchar(3)    default '',
		cr_vpar MEDIUMBLOB,
		cr_cavu varchar(13) default '',
		cr_dibp MEDIUMBLOB,
		cr_part MEDIUMBLOB,
		cr_mist MEDIUMBLOB,
		cr_vnfe varchar(13) default '',
		cr_vnpr decimal(6,2) default 0,
		cr_stat varchar(40) default '',
		cr_expe MEDIUMBLOB,
		cr_exse MEDIUMBLOB,
		cr_tabe MEDIUMBLOB,
		cr_chcp varchar(44) default '',
		cr_vobs MEDIUMBLOB,
		cr_deso MEDIUMBLOB,
		cr_twtp varchar(1) default '',
		cr_pdwb varchar(30) default '',
		cr_pdor varchar(3) default '',
		INDEX(cr_edav),
		INDEX(cr_ndav),
		INDEX(cr_erec),
		INDEX(cr_ecan),
		INDEX(cr_entr),
		INDEX(cr_nmcl),
		INDEX(cr_pdwb,cr_pdor));
		"""

bancos['clientes'] = """
		create table IF NOT EXISTS clientes (cl_regist int(8) not null auto_increment primary key,
		cl_nomecl varchar(100) default '',
		cl_fantas varchar(20) default '',
		cl_docume varchar(14) default '',
		cl_iestad varchar(15) default '',
		cl_pessoa varchar(01) default '',
		cl_fundac date,
		cl_cadast date,
		cl_endere varchar(45)  default '',
		cl_bairro varchar(20)  default '',
		cl_cidade varchar(20)  default '',
		cl_cdibge varchar(7)   default '',
		cl_cepcli varchar(9)   default '',
		cl_compl1 varchar(5)   default '',
		cl_compl2 varchar(20)  default '',
		cl_estado varchar(02)  default '',
		cl_emailc varchar(200) default '',                                                   
		cl_telef1 varchar(13)  default '',
		cl_telef2 varchar(13)  default '',
		cl_telef3 varchar(13)  default '',
		cl_eender varchar(45)  default '',
		cl_ebairr varchar(20)  default '',
		cl_ecidad varchar(20)  default '',
		cl_ecdibg varchar(7)   default '',
		cl_ecepcl varchar(9)   default '',
		cl_ecomp1 varchar(5)   default '',
		cl_ecomp2 varchar(20)  default '',
		cl_eestad varchar(02)  default '',
		cl_indefi varchar(5)   default '',
		cl_imunic varchar(15)  default '',
		cl_revend varchar(30)  default '',
		cl_seguim varchar(30)  default '',
		cl_refere text,
		cl_redeso text,
		cl_emails text,
		cl_pgfutu varchar(1)  default '',
		cl_limite decimal(15,2) default 0,
		cl_refeco text,
		cl_cdsimm varchar(15)   default '',
		cl_clmarc varchar(70)   default '',
		cl_rgparc varchar(8)    default '',
		cl_dtcomp date          default '00-00-0000',
		cl_dadosc varchar(200)  default '',
		cl_pgtofu text,
		cl_blcred text,
		cl_compra text,
		cl_codigo varchar(14)   default '',
		cl_dtincl date default '00-00-0000',
		cl_hrincl time default '00:00:00',
		cl_incalt varchar(1)   default '',
		cl_parame MEDIUMBLOB,
		cl_endent MEDIUMBLOB,
		cl_vended varchar(100) default '',
		cl_nmrede varchar(40)  default '',
		cl_altera MEDIUMBLOB,
		cl_agrega varchar(1)   default '',
		cl_ldados MEDIUMBLOB,
		cl_cdbanc varchar(8)   default '',
		cl_ccloud varchar(30) default '',
		cl_bloque varchar(1) default '',
		cl_urclie varchar(300) default '',
		cl_uscada varchar(50) default '',
		cl_lvorig varchar(3) default '');
		"""

bancos['receber'] = """
		create table IF NOT EXISTS receber (rc_regist int(8) not null auto_increment primary key,          
		rc_ndocum varchar(13)  default '',
		rc_origem varchar(1)   default '',
		rc_nparce varchar(2)   default '',
		rc_vlorin decimal(15,2) default 0,
		rc_apagar decimal(15,2) default 0,
		rc_formap varchar(30)  default '',
		rc_dtlanc date         default '00-00-0000',
		rc_hslanc time         default '00:00:00',
		rc_cdcaix varchar(4)   default '',
		rc_loginc varchar(12)  default '',
		rc_clcodi varchar(14)  default '',                                                   
		rc_clnome varchar(50)  default '',                                                   
		rc_clfant varchar(20)  default '',
		rc_cpfcnp varchar(14)  default '',
		rc_clfili varchar(3)   default '',
		rc_bxcaix varchar(4)   default '',
		rc_bxlogi varchar(12)  default '',
		rc_vlbaix decimal(15,2) default 0,
		rc_dtbaix date         default '00-00-0000',
		rc_hsbaix time         default '00:00:00',
		rc_formar varchar(40)  default '',
		rc_transp varchar(55)  default '',
		rc_trandh varchar(20)  default '',
		rc_indefi varchar(5)   default '',
		rc_idfcli varchar(5)   default '',
		rc_vencim date         default '00-00-0000',
		rc_bandei varchar(40)  default '',
		rc_chdocu varchar(20)  default '',
		rc_chcorr varchar(100) default '',
		rc_chbanc varchar(3)   default '',
		rc_chagen varchar(4)   default '',
		rc_chcont varchar(20)  default '',
		rc_chnume varchar(10)  default '',
		rc_chdado text,
		rc_status varchar(1)   default '',
		rc_canest text,
		rc_recebi varchar(1)   default '',
		rc_banbax varchar(40)  default '',
		rc_forbax varchar(30)  default '',
		rc_clcada varchar(1)   default '',
		rc_trocos decimal(15,2) default 0,
		rc_contac decimal(15,2) default 0,
		rc_sobrar decimal(15,2) default 0,
		rc_dtcanc date         default '00-00-0000',
		rc_hrcanc time         default '00:00:00',
		rc_cancod varchar(4)   default '',
		rc_canlog varchar(12)  default '',
		rc_destro decimal(15,2) default 0,
		rc_descon decimal(15,2) default 0,
		rc_dessob decimal(15,2) default 0,
		rc_desvin varchar(13)  default '',
		rc_relaca text,
		rc_baixat varchar(1)   default '',
		rc_estorn varchar(1)   default '',
		rc_modulo varchar(10)  default '',
		rc_vended varchar(12)  default '',
		rc_chcomp varchar(3)   default '',
		rc_autori varchar(20)  default '',
		rc_notafi varchar(9)   default '',
		rc_numcoo varchar(6)   default '',
		rc_acresc decimal(15,2) default 0,
		rc_dscnto decimal(15,2) default 0,
		rc_obsest text,
		rc_compro text,
		rc_cdvend varchar(4)  default '',
		rc_histor text,
		rc_boleto varchar(17) default '',
		rc_bolbar varchar(47) default '',
		rc_border varchar(10) default '',
		rc_databo date        default '00-00-0000',
		rc_horabo time        default '00:00:00',
		rc_loginu varchar(12) default '',
		rc_uscodi varchar(4)  default '',
		rc_instit varchar(60) default '',
		rc_rginst varchar(8)  default '',
		rc_docins varchar(14) default '',
		rc_borrtt text,
		rc_tipods varchar(1)   default '',
		rc_nosson varchar(20)  default '',
		rc_pgterc varchar(1)   default '',
		rc_bcobol varchar(100) default'',
		rc_dtbole date         default '00-00-0000',
		rc_hobole time         default '00:00:00',
		rc_fimtra varchar(50)  default '',
		rc_envfil varchar(50)  default '',
		rc_relapa text,
		rc_blweob MEDIUMBLOB,
		rc_littus varchar(1)   default '',
		INDEX (rc_dtlanc),
		INDEX (rc_dtbaix),
		INDEX (rc_vencim),
		INDEX (rc_status),
		INDEX (rc_cpfcnp));
		"""

bancos['conta'] = """
		create table IF NOT EXISTS conta (cc_regist int(8) not null auto_increment primary key,
		cc_lancam date         default '00-00-0000',
		cc_horala time         default '00:00:00',
		cc_usuari varchar(4)   default '',
		cc_usnome varchar(12)  default '',
		cc_cdfili varchar(3)   default '',
		cc_idfila varchar(5)   default '',
		cc_davlan varchar(13)  default '',
		cc_cdclie varchar(14)  default '',                                        
		cc_nmclie varchar(50)  default '',
		cc_docume varchar(14)  default '',
		cc_idfcli varchar(5)   default '',
		cc_origem varchar(2)   default '',
		cc_histor varchar(50)  default '',
		cc_credit decimal(15,2) default 0,
		cc_debito decimal(15,2) default 0,
		cc_saldos decimal(15,2) default 0,
		cc_fantas varchar(20)  default '',
		INDEX (cc_docume));
		"""

bancos['ocor'] = """
		create table IF NOT EXISTS ocorren (oc_regi int(8) not null auto_increment primary key,
		oc_docu varchar(20) default '',
		oc_usar varchar(60) default '',
		oc_corr text,
		oc_tipo varchar(20) default '',
		oc_inde varchar(5)  default '');
		"""

bancos['tdavs'] = """
		create table IF NOT EXISTS tdavs (tm_regi int(14) not null auto_increment primary key,
		tm_item varchar(3)    default '',
		tm_cont varchar(14)   default '',
		tm_codi varchar(14)   default '', 
		tm_nome varchar(120)   default '',  
		tm_quan decimal(15,4) default 0,
		tm_unid varchar(2)    default 'UN',   
		tm_prec decimal(15,3) default 0,
		tm_vlun decimal(15,4) default 0,
		tm_clcm decimal(6,3)  default 0,
		tm_clla decimal(6,3)  default 0,
		tm_clex decimal(6,3)  default 0,
		tm_clmt decimal(15,4) default 0,
		tm_ctcm decimal(6,3)  default 0,
		tm_ctla decimal(6,3)  default 0,
		tm_ctex decimal(6,3)  default 0,
		tm_ctmt decimal(15,4) default 0,
		tm_subt decimal(15,2) default 0,
		tm_unpc decimal(15,4) default 0,
		tm_mdct varchar(1)    default '1',
		tm_obsc text,
		tm_tiat varchar(1)    default '',
		tm_pibp decimal(5,2)  default 0,
		tm_fabr varchar(20)   default '',
		tm_ende varchar(30)   default '',  
		tm_barr varchar(14)   default '',  
		tm_cdfi varchar(30)   default '',
		tm_logi varchar(20)   default '',
		tm_lanc date          default '00-00-0000',
		tm_hora time          default '00:00:00',
		tm_tipo varchar(1)    default '',
		tm_clie varchar(14)   default '',                                      
		tm_tabe varchar(1)    default '',
		tm_cprc decimal(15,4) default 0,
		tm_cust decimal(15,2) default 0,
		tm_dado varchar(100)  default'',
		tm_fili varchar(5)    default'',
		tm_idpd varchar(8)    default'',
		tm_manu decimal(15,3) default 0,
		tm_auto text,
		tm_kitc varchar(220)  default'',
		tm_qkiv decimal(15,4) default 0,
		tm_ouin MEDIUMBLOB);
		"""

bancos['fornecedor'] = """
		create table IF NOT EXISTS fornecedor (fr_regist int(8) not null auto_increment primary key,
		fr_docume varchar(14) default '',
		fr_insces varchar(14) default '',
		fr_inscmu varchar(15) default '',
		fr_incnae varchar(7)  default '',
		fr_inscrt varchar(1)  default '',
		fr_nomefo varchar(120) default '',
		fr_fantas varchar(60) default '',
		fr_endere varchar(60) default '',
		fr_numero varchar(60) default '',
		fr_comple varchar(60) default '',
		fr_bairro varchar(60) default '',
		fr_cidade varchar(60) default '',
		fr_cepfor varchar(8)  default '',
		fr_estado varchar(2)  default '',
		fr_cmunuc varchar(7)  default '',
		fr_telef1 varchar(20) default '',                                      
		fr_telef2 varchar(20) default '',                                      
		fr_telef3 varchar(20) default '',                                      
		fr_fosite varchar(60) default '',
		fr_emails text,
		fr_contas text,
		fr_dtcada date default '00-00-0000',
		fr_idfila varchar(5)   default '',
		fr_tipofi varchar(1)   default '1',
		fr_bancof varchar(3)   default '',
		fr_agenci varchar(6)   default '',
		fr_contac varchar(11)  default '',
		fr_conven varchar(10)  default '',
		fr_especi varchar(5)   default '',
		fr_cartei varchar(5)   default '',
		fr_boleto varchar(1)   default 'F',
		fr_insbol text,
		fr_planoc varchar(20)  default '',
		fr_repres varchar(120) default '',
		fr_vplaca varchar(10)   default '',
		fr_vtipov varchar(60)   default '',
		fr_motori varchar(60)   default '',
		fr_manejo MEDIUMBLOB,
		fr_unpadr varchar(100) default '',
		fr_cargac decimal(15,3) default 0,
		fr_compri decimal(15,3) default 0,
		fr_parame MEDIUMBLOB);
		"""

bancos['ccmp'] = """
		create table IF NOT EXISTS ccmp (cc_regist int(10) not null auto_increment primary key,
		cc_docume varchar(14) default '',
		cc_nomefo varchar(120) default '',
		cc_fantas varchar(60) default '',
		cc_crtfor varchar(1)  default '',
		cc_ndanfe varchar(44) default '',
		cc_numenf varchar(9)  default '',
		cc_dtlanc date default '00-00-0000',
		cc_hrlanc time default '00:00:00',
		cc_uslanc varchar(12)   default '',
		cc_nfemis date default '00-00-0000',
		cc_nfdsai date default '00-00-0000',
		cc_nfhesa time default '00:00:00',
		cc_tprodu decimal(15,2) default 0,
		cc_baicms decimal(15,2) default 0,
		cc_vlicms decimal(15,2) default 0,
		cc_basest decimal(15,2) default 0,
		cc_valost decimal(15,2) default 0,
		cc_vfrete decimal(15,2) default 0,
		cc_vsegur decimal(15,2) default 0,
		cc_vdesco decimal(15,2) default 0,
		cc_valoii decimal(15,2) default 0,
		cc_valipi decimal(15,2) default 0,
		cc_valpis decimal(15,2) default 0,
		cc_vconfi decimal(15,2) default 0,
		cc_vodesp decimal(15,2) default 0,
		cc_vlrnfe decimal(15,2) default 0,
		cc_tipoes varchar(1)    default '',
		cc_filial varchar(5)    default '',
		cc_duplic text,
		cc_contro varchar(10)   default '',
		cc_itemsp varchar(4)    default '',
		cc_nserie varchar(3)    default '',
		cc_stantv decimal(15,2) default 0,
		cc_frantv decimal(15,2) default 0,
		cc_dsantv decimal(15,2) default 0,
		cc_emaile text,
		cc_protoc varchar(60)   default '',
		cc_fsegur decimal(15,2) default 0,
		cc_fdesac decimal(15,2) default 0,
		cc_tnffor decimal(15,2) default 0,
		cc_cancel text,
		cc_dtcanc date default '00-00-0000',
		cc_hrcanc time default '00:00:00',
		cc_uscanc varchar(12)   default '',
		cc_uccanc varchar(4)    default '',
		cc_status varchar(1)    default '',
		cc_icmfre decimal(15,2) default 0,
		cc_forige varchar(5)    default '',
		cc_fdesti varchar(5)    default '',
		cc_fimtra varchar(40)   default '',
		cc_envfil varchar(40)   default '',
		cc_corige varchar(10)   default '',
		cc_cdesti varchar(10)   default '',
		cc_acerto varchar(100)  default '',
		cc_ipiavu decimal(15,2) default 0,
		cc_stavul decimal(15,2) default 0,
		cc_basipi decimal(15,2) default 0,
		cc_infnfe text,
		cc_fremot varchar(5) default '',
		cc_manejo decimal(15,2) default 0,
		cc_unmane varchar(100) default '',
		cc_unmaid varchar(8) default '',
		cc_unnome varchar(100) default '',
		cc_unfant varchar(60) default '',
		cc_undocu varchar(14) default '',
		cc_idforn varchar(8)  default '',
		cc_apagar varchar(1)  default '');
		"""

bancos['iccmp'] = """
		create table IF NOT EXISTS iccmp (cc_regist int(10) not null auto_increment primary key,
		ic_contro varchar(10)   default '',
		ic_docume varchar(14)   default '',
		ic_nomefo varchar(120)   default '',
		ic_refere varchar(30)   default '',	                                         
		ic_cbarra varchar(14)   default '',	
		ic_descri varchar(120)  default '',	
		ic_codncm varchar(8)    default '',	
		ic_cdcfop varchar(4)    default '',	
		ic_unidad varchar(6)    default '',
		ic_quanti decimal(15,4) default 0,
		ic_quncom decimal(20,10) default 0,
		ic_vlrpro decimal(15,2) default 0,
		ic_untrib varchar(6)    default '',
		ic_qtribu decimal(15,4) default 0,
		ic_quatri decimal(20,10) default 0,
		ic_pedido varchar(15)   default '',
		ic_codcfi varchar(36)   default '',
		ic_origem varchar(1)    default '',
		ic_codcst varchar(3)    default '',
		ic_ccsosn varchar(3)    default '',
		ic_modicm varchar(1)    default '',
		ic_modcst varchar(1)    default '',
		ic_enqipi varchar(3)    default '',
		ic_bcicms decimal(15,2) default 0,
		ic_pricms decimal(5,2)  default 0,
		ic_vlicms decimal(15,2) default 0,
		ic_permva decimal(6,2)  default 0,
		ic_bascst decimal(15,2) default 0,
		ic_prstic decimal(6,2)  default 0,
		ic_valrst decimal(15,2) default 0,
		ic_cstipi varchar(3)    default '',
		ic_bscipi decimal(15,2) default 0,
		ic_peripi decimal(6,2)  default 0,
		ic_vlripi decimal(15,2) default 0,
		ic_cstpis varchar(3)    default '',
		ic_vbcpis decimal(15,2) default 0,
		ic_perpis decimal(6,2) default 0,
		ic_vlrpis decimal(15,2) default 0,
		ic_cstcof varchar(3)    default '',
		ic_bccofi decimal(15,2) default 0,
		ic_prcofi decimal(6,2) default 0,
		ic_vlrcof decimal(15,2) default 0,
		ic_lancam date default '00-00-0000',
		ic_horanl time default '00:00:00',
		ic_qtante decimal(15,4) default 0,
		ic_fabric varchar(20)   default '',
		ic_grupos varchar(20)   default '',
		ic_vcusto decimal(15,3) default 0,
		ic_qtunid decimal(15,4) default 0,
		ic_prdvin varchar(140)  default '',
		ic_stantp decimal(6,2)  default 0,
		ic_stantv decimal(15,2) default 0,
		ic_frantp decimal(6,2)  default 0,
		ic_frantv decimal(15,2) default 0,
		ic_dsantp decimal(6,2)  default 0,
		ic_dsantv decimal(15,2) default 0,
		ic_vlruni decimal(15,4) default 0,                                              
		ic_nregis varchar(8)    default '',
		ic_cdprod varchar(14)   default '',
		ic_subuni decimal(15,2) default 0,
		ic_medist decimal(6,2)  default 0,
		ic_pfsegu decimal(6,2)  default 0,
		ic_vfsegu decimal(15,2) default 0,
		ic_pfdsac decimal(6,2)  default 0,
		ic_vfdsac decimal(15,2) default 0,
		ic_esitem varchar(1)    default 'E',
		ic_dtcanc date default '00-00-0000',
		ic_hocanc time default '00:00:00',
		ic_uscanc varchar(12)   default '',
		ic_cdusca varchar(4)    default '',
		ic_cancel varchar(1)    default '',
		ic_qtanca decimal(15,4) default 0,
		ic_icmfrm decimal(6,2)  default 0,
		ic_icmfrv decimal(15,2) default 0,
		ic_filial varchar(5)    default "",
		ic_uslanc varchar(12)   default "",
		ic_cdusla varchar(4)    default "",
		ic_tipoen varchar(1)    default "",
		ic_fichae decimal(15,4) default 0,
		ic_forige varchar(5)    default '',
		ic_fdesti varchar(5)    default '',
		ic_ipipav decimal(6,2)  default 0,                                              
		ic_stpavu decimal(6,2)  default 0,
		ic_ipiavl decimal(15,4) default 0,
		ic_stavvl decimal(15,4) default 0,
		ic_cfisca varchar(30)   default '',
		ic_dadrma text,
		ic_fremot varchar(5) default '',
		ic_cmanej varchar(100)  default '',
		ic_vmanej decimal(15,2) default 0,
		ic_tmanej decimal(15,2) default 0,
		ic_unmaid varchar(8) default '',
		ic_unnome varchar(100) default '',
		ic_unfant varchar(40) default '',
		ic_undocu varchar(14) default '',
		ic_idforn varchar(8)  default '',
		ic_inftem MEDIUMBLOB,
		ic_locale varchar(1) default "",
		INDEX (ic_lancam),		
		INDEX (ic_dtcanc),
		INDEX (ic_lancam,ic_cdprod));		
		"""
		
bancos['apagar'] = """
		create table IF NOT EXISTS apagar (ap_regist int(10) not null auto_increment primary key,
		ap_docume varchar(14)   default '',
		ap_nomefo varchar(60)   default '',
		ap_fantas varchar(60)   default '',
		ap_ctrlcm varchar(10)   default '',
		ap_numenf varchar(9)    default '',
		ap_dtlanc date          default '00-00-0000',
		ap_hrlanc time          default '00:00:00',
		ap_usalan varchar(20)   default '',
		ap_dtvenc date          default '00-00-0000',
		ap_duplic varchar(40)   default '',
		ap_parcel varchar(2)    default '',
		ap_valord decimal(15,2) default 0,
		ap_dtbaix date          default '00-00-0000',
		ap_horabx time          default '00:00:00',
		ap_valorb decimal(15,2) default 0,
		ap_usabix varchar(20)   default '',
		ap_filial varchar(5)    default '',
		ap_dtcanc date          default '00-00-0000',
		ap_hocanc time          default '00:00:00',
		ap_usacan varchar(20)   default '',
		ap_status varchar(1)    default '',
		ap_cdusbx varchar(4)    default '',
		ap_cduslc varchar(4)    default '',
		ap_cdusca varchar(4)    default '',
		ap_chcorr varchar(150)  default '',
		ap_chbanc varchar(3)    default '',
		ap_chagen varchar(10)   default '',
		ap_chcont varchar(20)   default '',
		ap_chnume varchar(10)   default '',
		ap_jurosm decimal(15,2) default 0,
		ap_histor text,
		ap_estorn varchar(1)    default '',
		ap_border varchar(10)   default '',
		ap_pagame varchar(2)    default '',                                             
		ap_agrupa varchar(10)   default '',
		ap_cangru varchar(1)    default '',
		ap_lisagr text,
		ap_confer varchar(1)    default '',
		ap_hiscon text,
		ap_lanxml varchar(2)    default '',                                             
		ap_divers varchar(60)   default '',
		ap_descon decimal(15,2) default 0,
		ap_avalis varchar(120)  default '',
		ap_contas varchar(20)   default '',
		ap_fpagam text,
		ap_rgforn int(8)        default 0,
		ap_bterce varchar(10)   default '',
		ap_pacial varchar(13)   default '',
		ap_vlorig decimal(15,2) default 0,
		ap_bxparc varchar(1)    default'',
		ap_hisusa text,
		ap_uniman varchar(100)  default'',
		ap_grparc MEDIUMBLOB,
		ap_dtcomp date default '00-00-0000',
		INDEX (ap_dtlanc),
		INDEX (ap_dtvenc),
		INDEX (ap_dtbaix),
		INDEX (ap_dtcanc),
		INDEX (ap_dtcomp));
		"""

bancos['sangria'] = """
		create table IF NOT EXISTS sansu (ss_regist int(8) not null auto_increment primary key,
		ss_lancam date          default '00-00-0000',
		ss_horala time          default '00:00:00',
		ss_usnome varchar(12)   default '',
		ss_usreti varchar(12)   default '',
		ss_idfila varchar(5)    default '',
		ss_dinhei decimal(15,2) default 0,
		ss_chavis decimal(15,2) default 0,
		ss_chpred decimal(15,2) default 0,
		ss_credit decimal(15,2) default 0,
		ss_debito decimal(15,2) default 0,
		ss_ensaid varchar(1)    default '',
		ss_histor text);
		"""

bancos['perfil'] = """
		create table IF NOT EXISTS modperfil (mp_regist int(8) not null auto_increment primary key,
		mp_lancam date         default '00-00-0000',
		mp_horala time         default '00:00:00',
		mp_usnome varchar(12)  default '',
		mp_mdperf varchar(1)   default '',
		mp_perfil varchar(2)   default '',
		mp_modpai varchar(2)   default '',
		mp_mfilho varchar(4)   default '',
		mp_descri varchar(200) default '',
		mp_autori varchar(1)   default '');
		"""

bancos['autorizacao'] = """
		create table IF NOT EXISTS auremoto (au_regist int(8) not null auto_increment primary key,
		au_lancam varchar(1)   default '',
		au_dtpedi date         default '00-00-0000',
		au_hrpedi time         default '00:00:00',
		au_uspedi varchar(20)  default '',
		au_dtlibi date         default '00-00-0000',
		au_hrlibi time         default '00:00:00',
		au_uslibi varchar(20)  default '',
		au_histor text,
		au_solius varchar(20)  default '',
		au_comand varchar(15)  default '',
		au_descar varchar(1)   default '',
		au_hisant text,
		au_modulo varchar(2)   default '');
		"""

bancos['municipio'] = """
		create table IF NOT EXISTS municipio (mu_regist int(8) not null auto_increment primary key,
		mu_estado varchar(2)   default '',
		mu_codigo varchar(7)   default '',
		mu_munici varchar(200) default '');
		"""		

bancos['romaneio'] = """
		create table IF NOT EXISTS romaneio (rm_regist int(8) not null auto_increment primary key,
		rm_roman varchar(10)   default '',
		rm_abedt date          default '00-00-0000',
		rm_abehr time          default '00:00:00',
		rm_abeus varchar(12)   default '',
		rm_abecu varchar(4)    default '',
		rm_fecdt date          default '00-00-0000',
		rm_fechr time          default '00:00:00',
		rm_fecus varchar(12)   default '',
		rm_feccu varchar(4)    default '',
		rm_candt date          default '00-00-0000',
		rm_canhr time          default '00:00:00',
		rm_canus varchar(12)   default '',
		rm_cancu varchar(4)    default '',
		rm_qtdav int(4)        default 0,
		rm_relac text,
		rm_histo text,
		rm_cpfcn varchar(14)   default '',
		rm_motor varchar(60)   default '',
		rm_placa varchar(10)   default '',
		rm_tipov varchar(60)   default '',
		rm_kilom varchar(7)    default '',
		rm_dtent date          default '00-00-0000',
		rm_trans varchar(60)   default '',
		rm_ident varchar(8)    default '',
		rm_nosms varchar(100)  default '',
		INDEX(rm_roman),
		INDEX(rm_abedt),
		INDEX(rm_fecdt),
		INDEX(rm_candt),
		INDEX(rm_nosms));
		"""

bancos['nfe'] = """
		create table IF NOT EXISTS nfes (nf_regist int(10) not null auto_increment primary key,
		nf_nfesce varchar(1)   default '',
		nf_tipnfe varchar(1)   default '',
		nf_tipola varchar(1)   default '',
		nf_envdat date         default '00-00-0000',
		nf_envhor time         default '00:00:00',
		nf_envusa varchar(12)  default '',
		nf_retorn varchar(40)  default '',
		nf_rsefaz text,
		nf_rethor time         default '00:00:00',
		nf_numdav varchar(13)  default '',
		nf_oridav varchar(1)   default '',
		nf_candat date         default '00-00-0000',
		nf_canhor time         default '00:00:00',
		nf_canusa varchar(12)  default '',
		nf_canret varchar(40)  default '',
		nf_carhor time         default '00:00:00',
		nf_inndat date         default '00-00-0000',
		nf_innhor time         default '00:00:00',
		nf_innusa varchar(12)  default '',
		nf_innret varchar(40)  default '',
		nf_inrhor time         default '00:00:00',
		nf_ambien varchar(1)   default '',
		nf_idfili varchar(5)   default '',
		nf_protoc varchar(60)  default '',
		nf_nchave varchar(44)  default '',
		nf_nnotaf varchar(9)   default '',
		nf_codigc varchar(14)  default '',                                             
		nf_cpfcnp varchar(14)  default '',
		nf_fantas varchar(60)  default '',
		nf_clforn varchar(120) default '',
		nf_retcce varchar(40)  default '',
		nf_urlqrc MEDIUMBLOB,
		nf_nserie varchar(3)  default '',
		nf_emprot varchar(60) default '',
		nf_dgvalu varchar(60) default '',                                              
		nf_contig varchar(100) default '',
		nf_nconti varchar(1)  default '',
		nf_rconti varchar(160) default '',                                             
		nf_ncstat varchar(3)  default '',
		nf_prtcan MEDIUMBLOB,
		nf_vlnota decimal(15,2) default 0,
		INDEX(nf_envdat));
		"""

bancos['sefaz'] = """
		create table IF NOT EXISTS sefazxml (sf_regist int(10) not null auto_increment primary key,
		sf_numdav varchar(13) default '',
		sf_notnaf varchar(9)  default '',
		sf_xmlarq text,
		sf_pdfarq MEDIUMBLOB,                      
		sf_nchave varchar(44) default '',
		sf_tiponf varchar(1)  default '',
		sf_filial varchar(5)  default '',
		sf_codigo varchar(20) default '',
		sf_arqxml MEDIUMBLOB,
		INDEX(sf_nchave));
		"""

bancos['plcontas'] = """
		create table IF NOT EXISTS plcontas (pl_regist int(10) not null auto_increment primary key,
		pl_nconta varchar(20) default '',
		pl_dconta varchar(60) default '',
		pl_dcont3 varchar(60) default '',
		pl_dcont4 varchar(60) default '');
		"""

bancos['tmpclientes'] = """
		create table IF NOT EXISTS tmpclientes (tc_regist int(10) not null auto_increment primary key,
		tc_inform MEDIUMBLOB,
		tc_usuari varchar(20) default '',
		tc_quanti int(10) default 0,
		tc_vlrpro decimal(15,2) default 0,
		tc_quantf decimal(15,4) default 0,
		tc_vdcd varchar(4) default '',
		tc_nmvd varchar(12) default '',
		tc_vdcc varchar(4) default '',
		tc_nmvc varchar(12) default '',
		tc_inndat date default '00-00-0000',
		tc_fabr varchar(20) default '',  
		tc_ende varchar(30) default '',  
		tc_grup varchar(20) default '',
		tc_sbg1 varchar(20) default '',
		tc_sbg2 varchar(20) default '',
		tc_codi varchar(14) default '', 
		tc_barr varchar(14) default '',  
		tc_nome varchar(120) default '',  
		tc_unid varchar(2) default 'UN',
		tc_quantd decimal(15,4) default 0,
		tc_valor  decimal(15,2) default 0,
		tc_relat  varchar(5)    default '',
		tc_infor2 MEDIUMBLOB,
		tc_infor3 MEDIUMBLOB,
		tc_quant1 decimal(15,4) default 0,
		tc_quant2 decimal(15,4) default 0,
		tc_quant3 decimal(15,4) default 0,
		tc_hora   time default '00:00:00',
		tc_filial varchar(5) default "",
		tc_valor1 decimal(15,3) default 0,
		tc_valor2 decimal(15,2) default 0,
		tc_valor3 decimal(15,3) default 0,
		tc_obser1 varchar(100)  default '',
		tc_davctr varchar(14)   default '',
		tc_varia1 varchar(20)   default '',
		tc_clifor varchar(120)  default '',
		INDEX (tc_relat),
		INDEX (tc_nome),
		INDEX (tc_varia1,tc_relat));		
		"""

bancos['estoque'] = """
		create table IF NOT EXISTS estoque (ef_regist int(10) not null auto_increment primary key,
		ef_idfili varchar(5) default '',
		ef_codigo varchar(14) default '',
		ef_idprod varchar(8) default '',
		ef_fisico decimal(15,4)  not null default 0,
		ef_virtua decimal(15,4)  not null default 0,
		ef_trocas decimal(15,4)  not null default 0,
		ef_esloja decimal(15,4)  not null default 0,
		ef_endere varchar(30)  default '',
		INDEX (ef_codigo),
		INDEX (ef_idfili,ef_codigo));
		"""

bancos['frete'] = """
		create table IF NOT EXISTS fretes (ft_regist int(10) not null auto_increment primary key,
		ft_estado varchar(2) default '',
		ft_munici varchar(60) default '',
		ft_bairro varchar(60) default '',
		ft_valorf decimal(15,2)  not null default 0,
		ft_ajuste text);
		"""

bancos['entrega'] = """
		create table IF NOT EXISTS entregas (en_regist int(10) not null auto_increment primary key,
		en_filori varchar(5)  default '',
		en_filent varchar(5)  default '',
		en_numdav varchar(13) default '',
		en_ctrlor varchar(10) default '',
		en_ctrlet varchar(10) default '',
		en_qtante decimal(15,4) default 0,
		en_qtentr decimal(15,4) default 0,
		en_usentr varchar(12)   default '',
		en_uscanc varchar(12)   default '',
		en_entdat date         default '00-00-0000',
		en_enthor time         default '00:00:00',
		en_candat date         default '00-00-0000',
		en_canhor time         default '00:00:00',
		en_cdprod varchar(14)  default '',
		en_dsprod varchar(120) default '',
		en_portad varchar(120) default '');
		"""

bancos["notascompras"] = """
		create table IF NOT EXISTS comprasxml (nc_regist int(10) not null auto_increment primary key,
		nc_contro varchar(10)  default '',
		nc_notnaf varchar(9)   default '',
		nc_nchave varchar(44)  default '',
		nc_filial varchar(5)   default '',
		nc_entdat date         default '00-00-0000',
		nc_enthor time         default '00:00:00',
		nc_notdat date         default '00-00-0000',
		nc_nothor time         default '00:00:00',
		nc_usuari varchar(12)  default '',
		nc_nomefa varchar(100) default '',
		nc_nomefc varchar(200) default '',
		nc_docfor varchar(14)  default '',
		nc_valorn decimal(15,4) default 0,
		nc_arqxml MEDIUMBLOB,
		nc_cancel varchar(50)  default '',
		INDEX(nc_notnaf),
		INDEX(nc_nchave),
		INDEX(nc_filial),
		INDEX(nc_entdat));
		"""

bancos["relacionamentos"] = """
		create table IF NOT EXISTS relacionamento (rl_regist int(10) not null auto_increment primary key,
		rl_filial varchar(5) default '',
		rl_envios varchar(50)  default '',
		rl_status varchar(200) default '',
		rl_mensag MEDIUMBLOB,
		rl_envdat date        default '00-00-0000',
		rl_envhor time        default '00:00:00',
		rl_idenvi varchar(20) default '',
		rl_campan varchar(100) default '',
		rl_midias varchar(50) default '',
		rl_usuari varchar(12) default '',
		rl_nomecl varchar(120) default '',
		rl_telefo varchar(20) default '',
		rl_codigo varchar(14) default '',
		rl_refere varchar(50) default '',
		INDEX(rl_filial),
		INDEX(rl_envdat),
		INDEX(rl_midias),
		INDEX(rl_usuari),
		INDEX(rl_nomecl));
		"""

bancos["bancoscontas"] = """
		create table IF NOT EXISTS bancoconta (bc_regist int(14) not null auto_increment primary key,
		bc_docume varchar(50)  default '',
		bc_dlanca date         default '00-00-0000',
		bc_hlanca time         default '00:00:00',
		bc_idcada varchar(8)  default '',
		bc_planoc varchar(20)  default '',
		bc_valora decimal(15,2) default 0,
		bc_valorc decimal(15,2) default 0,
		bc_valord decimal(15,2) default 0,
		bc_valors decimal(15,2) default 0,
		bc_histor MEDIUMBLOB,
		bc_hiscur varchar(200)  default '',
		bc_filial varchar(5)  default '',
		bc_usuari varchar(20)  default '',
		bc_origem varchar(100)  default '',
		bc_tipola varchar(2)  default '',
		bc_bcorig varchar(200)  default '',
		bc_doccom varchar(20)  default '',
		bc_dtrefe date         default '00-00-0000',
		bc_docapa varchar(20)  default '',
		INDEX (bc_dlanca),
		INDEX (bc_idcada),
		INDEX (bc_planoc),
		INDEX (bc_dtrefe),
		INDEX (bc_docapa));
		"""

bancos["nfecompras"] = """
		create table IF NOT EXISTS nfecompras (nc_regi int(10) not null auto_increment primary key,
		nc_filial varchar(5)   default '',
		nc_dlanca date         default '00-00-0000',
		nc_hlanca time         default '00:00:00',
		nc_usuari varchar(12)  default '',
		nc_emissn varchar(50)  default '',
		nc_nchave varchar(44)  default '',
		nc_protoc varchar(30)  default '',
		nc_nvalor decimal(15,2) default 0,
		nc_xmldis varchar(1)   default '',
		nc_emcnpj varchar(14)  default '',
		nc_emnome varchar(120) default '',
		nc_numnsu int(15) default 0,
		nc_demiss date default '00-00-0000',
		nc_manife varchar(1) default '',
		nc_cancel varchar(100) default '',
		nc_arqxml MEDIUMBLOB,
		INDEX (nc_filial),
		INDEX (nc_dlanca),
		INDEX (nc_nchave),
		INDEX (nc_emcnpj),
		INDEX (nc_numnsu),
		INDEX (nc_demiss),
		INDEX (nc_xmldis),
		INDEX (nc_manife));
		"""

bancos['nfeoriginal'] = """
		create table IF NOT EXISTS nfeoriginal (no_regis int(10) not null auto_increment primary key,
		no_chave varchar(44)  default '',
		no_arxml MEDIUMBLOB,
		no_asxml MEDIUMBLOB,
		INDEX (no_chave));
		"""
		
bancos['mdfecadastros'] = """
		create table IF NOT EXISTS mdfecadastro (md_regis int(10) not null auto_increment primary key,
		md_codig varchar(2)  default '',
		md_cadas MEDIUMBLOB);
		"""
		
bancos['mdfecontrole']="""
		create table IF NOT EXISTS mdfecontrole (md_regis int(10) not null auto_increment primary key,
		md_filial varchar(5) default '',
		md_numdfe varchar(9) default '',
		md_ambien varchar(1) default '',
		md_nserie varchar(3) default '',
		md_cstatu varchar(3) default '',
		md_emissa date default '00-00-0000',
		md_horaem time default '00:00:00',
		md_usuari varchar(12) default '',
		md_ufinic varchar(2) default '',
		md_uffina varchar(2) default '',
		md_nchave varchar(44) default '',
		md_protoc varchar(30) default '',
		md_recibo varchar(30) default '',
		md_xmlmdf MEDIUMBLOB,
		md_xmlenc MEDIUMBLOB,
		md_xmlcan MEDIUMBLOB,
		md_xmlrej MEDIUMBLOB,
		md_status varchar(1) default '',
		md_usemis date default '00-00-0000',
		md_ushora time default '00:00:00',
		md_ususua varchar(12) default '',
		md_dadosu MEDIUMBLOB,
		md_relnfe MEDIUMBLOB,               
		INDEX (md_filial),
		INDEX (md_numdfe),
		INDEX (md_emissa),
		INDEX (md_nchave),
		INDEX (md_status));
		"""
		
bancos['individualcheque']="""		
	    create table IF NOT EXISTS individualcheque (ac_regis int(10) not null auto_increment primary key,
	    ac_filial varchar(5) default '',
	    ac_favore varchar(120) default '',
	    ac_emissa date default '00-00-0000',
	    ac_horaem time default '00:00:00',
	    ac_usuari varchar(12) default '',
	    ac_valord decimal(15,2) default 0,
	    ac_numero varchar(20) default '',
	    ac_tipola varchar(1) default '',
	    ac_liquid varchar(1) default '',
	    ac_xmlmdf MEDIUMBLOB,
	    ac_xmlenc MEDIUMBLOB,
	    ac_lifavo MEDIUMBLOB,
	    ac_vencim date default '00-00-0000',
	    ac_informd MEDIUMBLOB,
	    INDEX (ac_filial),
	    INDEX (ac_favore),
	    INDEX (ac_emissa),
	    INDEX (ac_numero),
	    INDEX (ac_vencim));
	    """
#---: Fim de defincao das tabelas
	
if sql[0] == True:

	if saida == 1:

		sequencia = 1
		for nome in bancos:

			print str( sequencia ).zfill(3)+("_"*50)+":"+nome
			sql[2].execute( bancos[nome] )
			sequencia +=1


	conn.cls( sql[1] )
